export const CONFIG = {
  PHRASE_INTERVAL: 12000,
  SOUND_INTERVAL: 18000,
  MOUSE_FLEE_DIST: 250,
  PHRASES: [
    "SALVA ESSE CÓDIGO AGORA.",
    "EU SEI O QUE VOCÊ FEZ.",
    "COMPILA DIREITO.",
    "PARA DE PROCRASTINAR.",
    "VOCÊ NÃO BEBEU ÁGUA.",
    "TESTE UNITÁRIO > DEPURAÇÃO",
    "CLEAN CODE AGORA!",
    'GIT COMMIT -m "WIP"',
    "CTRL+Z VAI SALVAR",
    "CAFÉ NA VEIA 🐟",
    "REFATORE ISSO AÍ",
    "NAO MEXA NO MAIN",
    "STACK OVERFLOW <3",
    "DEBUGAR É ARTE",
    "BEBA ÁGUA! 💧",
    "ARRUMA ESSA POSTURA! 🪑",
    "RESPIRA FUNDO...",
    "DESCANSA OS OLHOS 👀",
  ],
  HAPPY_PHRASES: ["NHAM NHAM!", "QUE DELÍCIA!", "TÔ FELIZ!", "OBRIGADO!", "❤"],
  TIME_PHRASES: {
    morning: ["HORA DO CAFÉ! ☕", "BOM DIA DE CÓDIGO!", "ACORDOU?"],
    afternoon: ["BOA TARDE!", "FOCO NO TRABALHO.", "MEIO DO DIA!"],
    evening: ["BOA NOITE DE CÓDIGO!", "HORA DO DESCANSO.", "DORMIR CEDO?"],
    friday: ["SEXTOU! 🎉", "FIM DE SEMANA CHEGANDO!", "SEXTA-FEIRA!"],
  },
  WORK_PHRASES: [
    "Bom trabalho.",
    "Foco no que importa.",
    "Pausa para respirar?",
    "Café ajuda.",
    "Tudo certo.",
    "Continue assim.",
    "Próximo passo.",
    "Organize as ideias.",
  ],
  PERSONALITIES: {
    CALMO: "calmo",
    TRAVESSO: "travesso",
    CAOTICO: "caotico",
  },
};
